# Generated by Django 5.1.3 on 2024-11-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('favorite', 'Favorite'), ('shopping_cart', 'Shopping Cart')], max_length=20)),
            ],
        ),
    ]
